import streamlit as st
import json
import os
import sys


# -------------------------------------------------
# ADD PROJECT ROOT TO PYTHON PATH
# -------------------------------------------------

PROJECT_ROOT = os.path.dirname(
    os.path.dirname(os.path.abspath(__file__))
)

if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)


# -------------------------------------------------
# IMPORT TRUST FUNCTIONS
# -------------------------------------------------

from blockchain.trust_score import (
    calculate_trust_score
)

from blockchain.review_verification import (
    get_reviews_by_product,
    calculate_average_rating
)

from blockchain.payment_service import (
    get_payments_by_wallet
)


# -------------------------------------------------
# PAGE CONFIGURATION
# -------------------------------------------------

st.set_page_config(
    page_title="Trust & Reputation | ShopWise AI",
    page_icon="🏆",
    layout="wide"
)


# -------------------------------------------------
# PAGE TITLE
# -------------------------------------------------

st.title("🏆 Trust & Reputation Dashboard")

st.write(
    "Explore product trust, verified customer feedback, "
    "and reputation signals generated by the ShopWise AI "
    "blockchain-inspired commerce system."
)

st.divider()


# -------------------------------------------------
# LOAD PRODUCTS
# -------------------------------------------------

PRODUCTS_FILE = os.path.join(
    PROJECT_ROOT,
    "data",
    "products.json"
)


def load_products():

    if not os.path.exists(PRODUCTS_FILE):
        return []

    try:

        with open(
            PRODUCTS_FILE,
            "r",
            encoding="utf-8"
        ) as file:

            return json.load(file)

    except (
        FileNotFoundError,
        json.JSONDecodeError
    ):

        return []


products = load_products()


# -------------------------------------------------
# CHECK PRODUCTS
# -------------------------------------------------

if not products:

    st.error(
        "❌ No products found. Please check "
        "data/products.json"
    )

else:

    # -------------------------------------------------
    # CALCULATE TRUST DATA FOR ALL PRODUCTS
    # -------------------------------------------------

    product_trust_data = []


    for product in products:

        product_id = product.get(
            "id"
        )

        trust_data = calculate_trust_score(
            product_id
        )

        reviews = get_reviews_by_product(
            product_id
        )

        average_rating = calculate_average_rating(
            product_id
        )


        product_trust_data.append(
            {
                "id": product_id,
                "name": product.get(
                    "name",
                    "Unknown Product"
                ),
                "price": product.get(
                    "price",
                    0
                ),
                "trust_score": trust_data.get(
                    "trust_score",
                    0
                ),
                "verified_reviews": len(
                    reviews
                ),
                "average_rating": average_rating
            }
        )


    # -------------------------------------------------
    # SORT BY TRUST SCORE
    # -------------------------------------------------

    product_trust_data = sorted(
        product_trust_data,
        key=lambda product:
            product["trust_score"],
        reverse=True
    )


    # -------------------------------------------------
    # PLATFORM SUMMARY
    # -------------------------------------------------

    st.header(
        "📊 Platform Trust Summary"
    )


    total_products = len(
        product_trust_data
    )


    total_reviews = sum(
        product["verified_reviews"]
        for product in product_trust_data
    )


    average_trust = 0

    if total_products > 0:

        average_trust = sum(
            product["trust_score"]
            for product in product_trust_data
        ) / total_products


    top_product = product_trust_data[0]


    col1, col2, col3, col4 = st.columns(
        4
    )


    col1.metric(
        "🛍️ Products",
        total_products
    )


    col2.metric(
        "⭐ Verified Reviews",
        total_reviews
    )


    col3.metric(
        "🛡️ Average Trust",
        f"{average_trust:.1f}/100"
    )


    col4.metric(
        "🏆 Most Trusted Product",
        top_product["name"]
    )


    st.divider()


    # -------------------------------------------------
    # TRUST LEADERBOARD
    # -------------------------------------------------

    st.header(
        "🏆 Product Trust Leaderboard"
    )


    for rank, product in enumerate(
        product_trust_data,
        start=1
    ):

        with st.container():

            col1, col2, col3, col4 = (
                st.columns(
                    [1, 3, 2, 2]
                )
            )


            with col1:

                st.markdown(
                    f"## #{rank}"
                )


            with col2:

                st.subheader(
                    product["name"]
                )

                st.caption(
                    f"Price: ₹{product['price']:,}"
                )


            with col3:

                st.metric(
                    "🛡️ Trust Score",
                    f"{product['trust_score']}/100"
                )


            with col4:

                st.metric(
                    "⭐ Verified Rating",
                    (
                        f"{product['average_rating']}"
                        "/5"
                    )
                )


            # TRUST PROGRESS BAR

            trust_progress = min(
                max(
                    product[
                        "trust_score"
                    ] / 100,
                    0
                ),
                1
            )


            st.progress(
                trust_progress
            )


            # TRUST LEVEL

            if product[
                "trust_score"
            ] >= 80:

                st.success(
                    "🟢 High Trust Product"
                )

            elif product[
                "trust_score"
            ] >= 50:

                st.info(
                    "🟡 Medium Trust Product"
                )

            else:

                st.warning(
                    "🔴 Building Trust"
                )


            st.caption(
                f"💬 {product['verified_reviews']} "
                "verified review(s)"
            )


            st.divider()


    # -------------------------------------------------
    # PRODUCT TRUST DETAILS
    # -------------------------------------------------

    st.header(
        "🔍 Explore Product Trust"
    )


    product_names = [
        product["name"]
        for product in product_trust_data
    ]


    selected_product_name = st.selectbox(
        "Select a product to inspect",
        product_names
    )


    selected_product = next(
        (
            product
            for product in product_trust_data
            if product["name"]
            == selected_product_name
        ),
        None
    )


    if selected_product:

        st.subheader(
            selected_product[
                "name"
            ]
        )


        col1, col2, col3 = st.columns(
            3
        )


        with col1:

            st.metric(
                "🛡️ Trust Score",
                (
                    f"{selected_product['trust_score']}"
                    "/100"
                )
            )


        with col2:

            st.metric(
                "⭐ Average Rating",
                (
                    f"{selected_product['average_rating']}"
                    "/5"
                )
            )


        with col3:

            st.metric(
                "💬 Verified Reviews",
                selected_product[
                    "verified_reviews"
                ]
            )


        st.markdown(
            "### 🧠 How Trust Is Used"
        )


        st.info(
            """
            ShopWise AI uses verified purchase and review
            signals to calculate product trust.

            Products with stronger verified feedback can receive
            a higher trust score and improve their position in
            AI-powered product recommendations.
            """
        )


# -------------------------------------------------
# INFORMATION
# -------------------------------------------------

st.divider()

st.caption(
    "🔗 ShopWise AI Trust & Reputation System — "
    "Blockchain-inspired verified purchases and "
    "verifiable customer feedback."
)